services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
    ports:
      - 9999:9999
    restart: always
    
  server1: &server
    hostname: server1
    build:
      context: ./
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always
    
  server2:
    <<: *server
    hostname: server2

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    restart: always

volumes:
  postgres: