services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    env_file:
      - ./.env
    ports:
      - 5432:${POSTGRES_PORT}

volumes:
  postgres: