services:
  server:
    build:
      context: ./
    env_file:
      - ./.env
    ports:
      - 8000:${SERVER_PORT}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always

volumes:
  postgres: